### ISSUE TITLE
Cytoscape Zooming via Mouse Wheel

### ISSUE THREAD

**Issue by georg-schwarz** [osrgroup/msadoc#116] opened 2022-12-15 12:19 UTC
- Seems to differ on users
- Could be a bit more fine-granular

**Comment by MBuchalik** [comment] 2022-12-15 18:34
In order to control the mouse sensitivity, you need to use the `wheelSensitivity` Prop. Once I set it to `0.2`, zooming worked much better on my machine. However, when you do this, you get a warning in the dev console:
![grafik](https://user-images.githubusercontent.com/8061217/207939995-ab27120c-505f-4abb-9ae9-b7985b8668ef.png)

So I guess it is pretty likely that it is caused by my setup. Should we close this issue?

**Comment by georg-schwarz** [comment] 2022-12-15 19:50
Probably, yes ^^
Thx for looking into it!

**Comment by georg-schwarz** [comment] 2023-02-02 13:04
Seems to be an issue again/still?

**Closed** 2023-02-03 13:49 UTC
